services:
  api:
    build: .
    container_name: api
    ports:
      - "8000:8000"
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1